# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from seigr_protocol import utils_pb2 as src_dot_seigr__protocol_dot_utils__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/seigr_protocol/utils_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UtilitiesServiceStub(object):
    """Utilities service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformUtilityOperation = channel.unary_unary(
                '/seigr.utils.UtilitiesService/PerformUtilityOperation',
                request_serializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityRequest.SerializeToString,
                response_deserializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.FromString,
                _registered_method=True)
        self.ValidateData = channel.unary_unary(
                '/seigr.utils.UtilitiesService/ValidateData',
                request_serializer=src_dot_seigr__protocol_dot_utils__pb2.ValidationRequest.SerializeToString,
                response_deserializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.FromString,
                _registered_method=True)


class UtilitiesServiceServicer(object):
    """Utilities service
    """

    def PerformUtilityOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilitiesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformUtilityOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformUtilityOperation,
                    request_deserializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityRequest.FromString,
                    response_serializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.SerializeToString,
            ),
            'ValidateData': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateData,
                    request_deserializer=src_dot_seigr__protocol_dot_utils__pb2.ValidationRequest.FromString,
                    response_serializer=src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seigr.utils.UtilitiesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seigr.utils.UtilitiesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UtilitiesService(object):
    """Utilities service
    """

    @staticmethod
    def PerformUtilityOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seigr.utils.UtilitiesService/PerformUtilityOperation',
            src_dot_seigr__protocol_dot_utils__pb2.UtilityRequest.SerializeToString,
            src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seigr.utils.UtilitiesService/ValidateData',
            src_dot_seigr__protocol_dot_utils__pb2.ValidationRequest.SerializeToString,
            src_dot_seigr__protocol_dot_utils__pb2.UtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
