# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/seigr_protocol/utils.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'src/seigr_protocol/utils.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esrc/seigr_protocol/utils.proto\x12\x0bseigr.utils\"\xb1\x01\n\x11ValidationRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x17\n\x0fvalidation_type\x18\x02 \x01(\t\x12\x42\n\nparameters\x18\x03 \x03(\x0b\x32..seigr.utils.ValidationRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xca\x01\n\x0eUtilityRequest\x12\x30\n\toperation\x18\x01 \x01(\x0e\x32\x1d.seigr.utils.UtilityOperation\x12\x12\n\ninput_data\x18\x02 \x01(\x0c\x12?\n\nparameters\x18\x03 \x03(\x0b\x32+.seigr.utils.UtilityRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbd\x01\n\x0fUtilityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_data\x18\x02 \x01(\x0c\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12<\n\x08metadata\x18\x04 \x03(\x0b\x32*.seigr.utils.UtilityResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x87\x01\n\x10UtilityOperation\x12\x10\n\x0cUTIL_UNKNOWN\x10\x00\x12\x11\n\rVALIDATE_DATA\x10\x01\x12\x11\n\rENCODE_STRING\x10\x02\x12\x11\n\rDECODE_STRING\x10\x03\x12\x14\n\x10\x43\x41LCULATE_ENERGY\x10\x04\x12\x12\n\x0e\x43ONVERT_FORMAT\x10\x05\x32\xb6\x01\n\x10UtilitiesService\x12T\n\x17PerformUtilityOperation\x12\x1b.seigr.utils.UtilityRequest\x1a\x1c.seigr.utils.UtilityResponse\x12L\n\x0cValidateData\x12\x1e.seigr.utils.ValidationRequest\x1a\x1c.seigr.utils.UtilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.seigr_protocol.utils_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATIONREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_VALIDATIONREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_UTILITYREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_UTILITYREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_UTILITYRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_UTILITYRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UTILITYOPERATION']._serialized_start=625
  _globals['_UTILITYOPERATION']._serialized_end=760
  _globals['_VALIDATIONREQUEST']._serialized_start=48
  _globals['_VALIDATIONREQUEST']._serialized_end=225
  _globals['_VALIDATIONREQUEST_PARAMETERSENTRY']._serialized_start=176
  _globals['_VALIDATIONREQUEST_PARAMETERSENTRY']._serialized_end=225
  _globals['_UTILITYREQUEST']._serialized_start=228
  _globals['_UTILITYREQUEST']._serialized_end=430
  _globals['_UTILITYREQUEST_PARAMETERSENTRY']._serialized_start=176
  _globals['_UTILITYREQUEST_PARAMETERSENTRY']._serialized_end=225
  _globals['_UTILITYRESPONSE']._serialized_start=433
  _globals['_UTILITYRESPONSE']._serialized_end=622
  _globals['_UTILITYRESPONSE_METADATAENTRY']._serialized_start=575
  _globals['_UTILITYRESPONSE_METADATAENTRY']._serialized_end=622
  _globals['_UTILITIESSERVICE']._serialized_start=763
  _globals['_UTILITIESSERVICE']._serialized_end=945
# @@protoc_insertion_point(module_scope)
